### ISSUE TITLE
Contract Changes

### ISSUE THREAD

**Issue by MoeNick** [divine-comedian/PFPtest#7]
- [x] If someone transfers ETH to the contract we can’t claim - we should sort out a backup here
- [x] Transfer of funds only go to 1 address but anyone can call it. Only goes to owner.
- [x] Will add a function for withdrawing ETH

**Comment by MoeNick** [comment]
I created this according to @Santigs 's feedback. please correct me if I have missed something.

**Comment by divine-comedian** [comment]
this has all been implemented and tests have been built for receiving and withdrawing ETH

**Comment by MoeNick** [comment]
Do we need to QA it? does  @aminlatifi take it ? :)

**Comment by aminlatifi** [comment]
> Do we need to QA it? does @aminlatifi take it ? :)
I and @divine-comedian have done most of it, it's better another person do the QA if possible
@KurtMerbeth Is the best I think

**Comment by divine-comedian** [comment]
here:
https://github.com/Giveth/PFPtest/blob/master/contracts/GiversPFP.sol

still need to merge #8

**Comment by divine-comedian** [comment]
from Kurt:

withdrawAndChangePaymentToken this function pretty smart

setBaseURI enables you to change the meta data whenever you want. it's usually not really trustworthy.

to same some gas, you could refactor all for loops to have an unchecked block like lines 117-119

(mintAmount_ > maxMintAmount)
just a logic qustion: maxMintAmount is the amount a user can mint in one transaction. if it's set to 5, and i make 10 transactions I can still mint 50 pfps, is that correct?  If not, you could check the users pfp balance + mintAmount < maxMintAmount

but that's it, i don't see any major things, looks good for me.
[8:28 AM]
oh, you could add an event for setAllowListOnly
